version: '2'
# login: user
# password: bitnami
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    image: dirame/jenkins-docker-ansible-clair
    ports:
      - '80:8080'
      - '443:8443'
      - '5000:5000'
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_home:/opt/'
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local
